[tox]
requires =
    tox>=4
env_list = lint, py{312,313,314}-django{50,52,60}


[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314


[testenv]
description = run unit tests
setenv =
    DJANGO_SETTINGS_MODULE=test_project.settings.test
deps =
    pytest>=7
    pytest-django
    pytest-cov
    dramatiq
    django-dramatiq
    requests
    pydantic
    django50: Django>=5.0,<5.1
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
commands =
    pytest --cov --cov-report xml {posargs:tests}
usedevelop = True

[testenv:lint]
description = run linters
skip_install = true
deps =
    ruff==0.15.1
changedir = django_ctb
commands =
    ruff check --diff --no-fix
    ruff format --diff --check
