# Generated by Django 6.0.2 on 2026-04-05 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ctb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuildpartshortage',
            name='fallback_part',
            field=models.ForeignKey(blank=True, help_text='This part will be used to cover this shortage upon re-clearing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortage_fallback_parts', to='django_ctb.part'),
        ),
        migrations.AlterField(
            model_name='projectpart',
            name='substitute_part',
            field=models.ForeignKey(blank=True, help_text='When set, the substitute part will be used instead of the actual part', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitute_project_parts', to='django_ctb.part'),
        ),
    ]
