# Generated by Django 5.0.6 on 2024-12-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ctb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectbuild",
            name="excluded_project_parts",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"is_optional": True},
                to="django_ctb.projectpart",
            ),
        ),
        migrations.AddField(
            model_name="projectpart",
            name="is_optional",
            field=models.BooleanField(default=False),
        ),
    ]
