# Generated by Django 6.0.2 on 2026-04-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ctb', '0002_projectbuildpartshortage_fallback_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuildpartreservation',
            name='order_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectbuildpartshortage',
            name='fallback_part',
            field=models.ForeignKey(blank=True, help_text='Part to be used to cover this shortage upon re-clearing', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortage_fallback_parts', to='django_ctb.part'),
        ),
    ]
