# Generated by Django 5.0.6 on 2025-01-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ctb", "0002_projectbuild_excluded_project_parts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="equivalent_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equivalents",
                to="django_ctb.part",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryaction",
            name="inventory_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_actions",
                to="django_ctb.inventoryline",
            ),
        ),
        migrations.AlterField(
            model_name="projectbuild",
            name="excluded_project_parts",
            field=models.ManyToManyField(blank=True, to="django_ctb.projectpart"),
        ),
    ]
