# Generated by Django 6.0.2 on 2026-05-10 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ensure_owner(apps, schema_editor):
    Owner = apps.get_model("django_ctb", "Owner")
    Owner.objects.get_or_create(id=1)


class Migration(migrations.Migration):
    dependencies = [
        ("django_ctb", "0003_projectbuildpartreservation_order_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="django_ctb_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(ensure_owner, migrations.RunPython.noop),
    ]
