# Generated by Django 6.0.2 on 2026-05-15 15:12

import django.db.migrations.operations.special
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# django_ctb.migrations.0004_owner


def ensure_owner(apps, schema_editor):
    Owner = apps.get_model("django_ctb", "Owner")
    Owner.objects.get_or_create(id=1)


class Migration(migrations.Migration):
    replaces = [
        ("django_ctb", "0004_owner"),
        ("django_ctb", "0005_implicitprojectpart_owner_inventory_owner_and_more"),
        ("django_ctb", "0006_alter_implicitprojectpart_owner_and_more"),
        ("django_ctb", "0007_remove_inventoryline_inventory_and_more"),
        ("django_ctb", "0008_alter_inventoryline_owner"),
    ]

    dependencies = [
        ("django_ctb", "0003_projectbuildpartreservation_order_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="django_ctb_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=ensure_owner,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="implicitprojectpart",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_ctb.owner",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="django_ctb.owner",
            ),
        ),
        migrations.AddField(
            model_name="vendororder",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="django_ctb.owner",
            ),
        ),
        migrations.AddField(
            model_name="inventoryline",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="django_ctb.owner",
            ),
        ),
        migrations.RemoveField(
            model_name="inventoryline",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="vendororderline",
            name="for_inventory",
        ),
        migrations.AlterField(
            model_name="vendorpart",
            name="lot_cost",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("cost"), "*", models.F("volume")
                ),
                output_field=models.DecimalField(decimal_places=4, max_digits=12),
            ),
        ),
        migrations.AlterField(
            model_name="vendorpart",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_parts",
                to="django_ctb.part",
            ),
        ),
        migrations.AlterField(
            model_name="implicitprojectpart",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="django_ctb.owner"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="django_ctb.owner"
            ),
        ),
        migrations.AlterField(
            model_name="vendororder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="django_ctb.owner"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryline",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="django_ctb.owner"
            ),
        ),
        migrations.DeleteModel(
            name="Inventory",
        ),
    ]
