# Generated by Django 5.0.6 on 2025-04-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ctb', '0003_part_equivalent_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbuildpartreservation',
            name='project_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='django_ctb.projectpart'),
        ),
    ]
