# Generated by Django 6.0.2 on 2026-05-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ctb', '0004_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='implicitprojectpart',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='django_ctb.owner'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_ctb.owner'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_ctb.owner'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='django_ctb.owner'),
        ),
    ]
