# Generated by Django 5.0.6 on 2025-04-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ctb', '0004_projectbuildpartreservation_project_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectversion',
            name='parts',
        ),
        migrations.AddField(
            model_name='projectpart',
            name='substitute_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='substitute_project_part', to='django_ctb.part'),
        ),
    ]
