# Generated by Django 6.0.2 on 2026-05-11 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ctb', '0005_implicitprojectpart_owner_inventory_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implicitprojectpart',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ctb.owner'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ctb.owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ctb.owner'),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ctb.owner'),
        ),
    ]
