# Generated by Django 5.0.6 on 2025-12-31 17:17

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ctb", "0005_remove_projectversion_parts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendororder",
            name="placed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorpart",
            name="lot_cost",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("cost"), "*", models.F("volume")
                ),
                output_field=models.DecimalField(decimal_places=4, max_digits=8),
            ),
        ),
    ]
