from __future__ import annotations

import logging
from collections.abc import Callable
from typing import TYPE_CHECKING

from docutils import nodes
from docutils.statemachine import StringList
from sphinx.util.docutils import SphinxDirective, switch_source_input
from sphinx.util.parsing import nested_parse_to_nodes

from .documenters import BDDModuleDocumenter, DocumenterBridge, Options

if TYPE_CHECKING:
    from docutils.nodes import Node
    from docutils.parsers.rst.states import RSTState

logger = logging.getLogger(__name__)


class DummyOptionSpec(dict[str, Callable[[str], str]]):  # NoQA: FURB189
    """An option_spec allows any options."""

    def __bool__(self) -> bool:
        """Behaves like some options are defined."""
        return True

    def __getitem__(self, _key: str) -> Callable[[str], str]:
        return lambda x: x


def parse_generated_content(
    state: RSTState, content: StringList, titles_allowed: bool
) -> list[Node]:
    """Parse an item of content generated by _auto_document_object()."""
    with switch_source_input(state, content):
        if titles_allowed:
            return nested_parse_to_nodes(state, content)

        node = nodes.paragraph()
        # necessary so that the child nodes get the right source/line set
        node.document = state.document
        state.nested_parse(content, 0, node, match_titles=False)
        return node.children


class BDDModuleDirective(SphinxDirective):
    """
    Directive for referencing a python module for BDD Feature and Scenario
    extraction usage like::

      .. bddmodule:: <python.path.to.module>

    Generates more primitive ``bdd:feature`` and ``bdd:scenario`` directives
    from properly formatted docstrings in the named python module.
    """

    option_spec = DummyOptionSpec()
    has_content = True
    required_arguments = 1
    optional_arguments = 0
    final_argument_whitespace = True

    def run(self) -> list[Node]:
        # boilerplate
        reporter = self.state.document.reporter
        source, lineno = self.get_source_info()

        # process options (none for now)
        params = DocumenterBridge(
            self.env,
            reporter,
            Options(),
            lineno,
            self.state,
        )
        documenter = BDDModuleDocumenter(params, self.arguments[0])
        documenter.generate(more_content=self.content)
        result = parse_generated_content(self.state, params.result, False)
        return result
